AirOpsWeather = AirOpsWeather or {}
local cache={valid=false,currentWeather=Config.Weather.fallback,previousWeather=nil,weatherClass='normal',raw={},forecast={},timezoneOffsetSeconds=0,fetchedAt=0,weatherChangedAt=0,nextPollAt=0,failureCount=0}
function AirOpsWeather.GetCache() return cache end
function AirOpsWeather.SetSuccessfulFetch(payload) cache.valid=true cache.raw=payload.current or {} cache.forecast=payload.forecast or {} cache.timezoneOffsetSeconds=tonumber(payload.timezoneOffsetSeconds) or 0 cache.fetchedAt=os.time() cache.failureCount=0 end
function AirOpsWeather.SetWeather(weather,class) local now=os.time() if weather~=cache.currentWeather then cache.previousWeather=cache.currentWeather cache.currentWeather=weather cache.weatherChangedAt=now elseif cache.weatherChangedAt==0 then cache.weatherChangedAt=now end cache.weatherClass=class or 'normal' end
function AirOpsWeather.CanChangeWeather(candidate) if candidate==cache.currentWeather or cache.weatherChangedAt==0 then return true end return (os.time()-cache.weatherChangedAt)>=Config.Weather.minimumStateDurationSeconds end
function AirOpsWeather.RegisterFailure() cache.failureCount=cache.failureCount+1 return cache.failureCount end
function AirOpsWeather.SetNextPoll(ts) cache.nextPollAt=ts end
function AirOpsWeather.PublicState() return {version=AirOpsWeather.Version,valid=cache.valid,serverUnixTime=os.time(),timezoneOffsetSeconds=cache.timezoneOffsetSeconds,currentWeather=cache.currentWeather,previousWeather=cache.previousWeather,weatherChangedAt=cache.weatherChangedAt,transitionSeconds=Config.Weather.transitionSeconds,windSpeed=tonumber(cache.raw.windSpeed) or 0.0,windDirection=tonumber(cache.raw.windDirection) or 0.0,windGusts=tonumber(cache.raw.windGusts) or 0.0,temperature=tonumber(cache.raw.temperature),fetchedAt=cache.fetchedAt} end
